version: '3.4'

services:

    router:
        image: binocarlos/noxy
        ports:
            - 80:80
        container_name: router
        environment:
            - NOXY_DEFAULT_HOST=ui
            - NOXY_DEFAULT_PORT=3030
            - NOXY_DEFAULT_WS=1
            - NOXY_API_FRONT=/api
            - NOXY_API_HOST=server
            - NOXY_API_PORT=9000
        networks:
            - react_dashboard_network

    ui:
        image: ${UI_IMAGE_NAME}:${IMAGE_TAG}
        container_name: ui
        expose:
            - 3030
        ports:
            - 3030:3030
        volumes:
            - ../ui/src:/opt/src
        networks:
            - react_dashboard_network

    server:
        image: ${SERVER_IMAGE_NAME}:${IMAGE_TAG}
        container_name: server
        expose:
            - 9000
        ports:
            - 9000:9000
        volumes: 
            - ../server/src:/opt/src
        networks:
            - react_dashboard_network

networks:
    react_dashboard_network:
